-- Create company_profiles table
CREATE TABLE IF NOT EXISTS company_profiles (
  id SERIAL PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL,
  cage_code VARCHAR(50),
  sam_uei VARCHAR(50),
  sam_registered BOOLEAN DEFAULT false,
  naics_code VARCHAR(50),
  naics_size VARCHAR(100),
  business_type VARCHAR(50),
  small_disadvantaged BOOLEAN DEFAULT false,
  woman_owned BOOLEAN DEFAULT false,
  veteran_owned BOOLEAN DEFAULT false,
  service_disabled_vet_owned BOOLEAN DEFAULT false,
  hub_zone BOOLEAN DEFAULT false,
  historically_underutilized BOOLEAN DEFAULT false,
  alaska_native_corp BOOLEAN DEFAULT false,
  default_payment_terms VARCHAR(100),
  default_payment_terms_other VARCHAR(255),
  default_fob VARCHAR(50),
  default_purchase_order_min NUMERIC(10, 2),
  default_complimentary_freight BOOLEAN DEFAULT false,
  default_ppa_by_vendor BOOLEAN DEFAULT false,
  contact_person VARCHAR(255),
  contact_email VARCHAR(255),
  contact_phone VARCHAR(50),
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);